name: build

on:
  workflow_dispatch:
  push:
    tags:
      - '*'
    branches:
      - main
      - develop
      - "release/*"
  pull_request:
  release:
    types:
      - published

jobs:
  dist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5

      - name: Build SDist and wheel
        run: pipx run --spec build pyproject-build

      - name: Check metadata
        run: pipx run twine check dist/*

      - uses: actions/upload-artifact@v4
        with:
            path: dist/*

  publish:
      needs: [ dist ]
      environment: pypi
      permissions:
          id-token: write
      runs-on: ubuntu-latest
      if: github.event_name == 'release' && github.event.action == 'published'
      steps:
          - uses: actions/download-artifact@v4.1.8
            with:
                name: artifact
                path: dist

          - uses: pypa/gh-action-pypi-publish@release/v1
